---
name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.15, 1.16]

    build:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v
        working-directory: cmd/api

      - name: Test
        run: go test -v ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chatterino-api-${{ matrix.go }}
          path: cmd/api/api
