---
name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: test2
        if: (github.event_name  == 'push' && github.ref == 'refs/heads/master')
        run: |
            echo "XD 2"

      - name: test3
        run: |
            echo "${{ github.event_name }}"
            echo "${{ github.ref }}"
            echo "$GITHUB_CONTEXT"
            echo "asd 12345"

      - name: Create release (All platforms)
        id: create_release
        uses: pajlada/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          backup_tag_name: nightly-backup
          release_name: NIGHTLY RELEASE
          body: |
            Changes in this Release XD
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: test
        env:
          CI_UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
        run: |
            echo "$CI_UPLOAD_URL" > release-upload-url.txt

      - uses: actions/upload-artifact@v1
        with:
          name: release-upload-url.txt
          path: release-upload-url.txt

  upload-release:
    needs: create-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/download-artifact@v1
        with:
          name: release-upload-url.txt

      - uses: ./.github/actions/read-upload-url
        id: upload_url
        with:
          file: release-upload-url.txt/release-upload-url.txt

      - name: test
        id: test
        run: |
            echo "::set-output name=test::$(cat release-upload-url.txt/release-upload-url.txt)"

      - name: XD
        env:
          TEST: ${{ steps.upload_url.outputs.data }}
          TEST2: ${{ steps.test.outputs.test }}
        run: |
            echo "a: '$TEST'"
            echo "b: '$TEST2' XD"
